### ISSUE TITLE
Problem while deploying a ver 4.3 manual installation

### ISSUE THREAD

**Issue by satamazing** [bacularis/bacularis-web#7] opened 2024-10-29 11:07 UTC
Hello. 

When deploying a new manual installation for version 4.3 I get this error while installing Catalog:

===== Step: Install Catalog =====

Software managment command is not configured.
Software managment command is not configured.
Software managment command is not configured.

Thanks you so much.

Best Regards

**Comment by ganiuszka** [comment] 2024-10-29 12:17
Hello @satamazing,

Thank you for your report.

Yes, it looks that something is wrong. I think we will need additional details.

Could you tell me what is your operating system and if SELinux is enabled? If it is enabled, then what is the bacularis.pp SELinux module version that you loaded? You can check it inside the bacularis.te file in the first line.

Thanks in advance.

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment] 2024-10-29 12:25
Hello @ganiuszka 

Thanks for the quick replay!

I am using a Debian 12 installed over a VM with no SELinux installed

Let me know if there is any other info I should provide.

Thanks again 

Regards

Julen (@satamazing )

**Comment by ganiuszka** [comment] 2024-10-29 14:15
Hello Julen ( @satamazing ),

Thanks for response and details. I think we have everything now.

I was able to reproduce it. This is a problem with application paths. In the install wizard are used paths from pre-defined OS profiles. Unfortunately on the install wizard level we are not able to create new OS profiles yet where we could adapt paths. It is possible after installation.

As a solution I added a documentation section to the manual installation chapter where are commands that solve this problem. You can find it here:

https://bacularis.app/doc/brief/installation.html#optional-commands

To read it, you may need to refresh the web browser cache, because I updated the documentation at bacularis.app at the moment. But you will see.

To the manual installation I added also the ``expect`` program to the installed Bacularis dependencies because it was missing there.

To fix your installation on VM, please move somewhere or remove this directory in your VM:

/etc/bacularis

and then you can execute these new optional commands from the documentation.

At the end you should be able to install Bacula through Bacularis.

Please let us know if it helped. Thanks!

Best regards,
Marcin Haba (gani)

**Comment by satamazing** [comment] 2024-10-29 14:48
Hello gani @ganiuszka 

I just followed your new instructions and the systems had been installed successfully!!

Thank you very much.

Wish you all the words luck with the project.

Julen @satamazing

**Comment by ganiuszka** [comment] 2024-10-29 14:53
Many thanks, Julen :smile: 

That is great it started working.

I am closing this issue.

Best regards,
Marcin Haba (gani)

**Closed as completed by ganiuszka** 2024-10-29 14:53 UTC
Labels: documentation
